version: '3.2'

services:
  tax-nginx:
    image: nginx:latest
    container_name: tax-nginx
    ports:
      - "8888:80"
      - "4443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt
      - ./nginx/certs/nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key
      - ./static:/usr/share/nginx/html
    networks:
      - tnet

  tax-db:
    image: mdillon/postgis
    container_name: tax-db
    volumes:
      #- ./db-init:/docker-entrypoint-initdb.d
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - '15432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_DB: taxonomy
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    command: [ "postgres", "-c", "wal_level=logical" ]
    networks:
      - tnet

volumes:
  dbdata:

networks:
  tnet:
    driver: bridge
