version: '3.2'

services:
  tax-nginx:
    image: nginx:latest
    container_name: tax-nginx
    ports:
      - "8888:80"
      - "4443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt
      - ./nginx/certs/nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key
      - ./static:/usr/share/nginx/html
    networks:
      - tnet

  tax-db:
    image: mdillon/postgis
    container_name: tax-db
    volumes:
      #- ./db-init:/docker-entrypoint-initdb.d
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - '15432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_DB: taxonomy
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    command: [ "postgres", "-c", "wal_level=logical" ]
    networks:
      - tnet

  couchbase-server:
    build: ./couchbase
    container_name: couchbase-server
    hostname: couchbase-server
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    environment:
      - CLUSTER_NAME=taxonomy
      - COUCHBASE_ADMINISTRATOR_USERNAME=test
      - COUCHBASE_ADMINISTRATOR_PASSWORD=test
      - COUCHBASE_BUCKET=products
      - COUCHBASE_BUCKET_RAMSIZE=512
      - COUCHBASE_RAM_SIZE=2048
      - COUCHBASE_INDEX_RAM_SIZE=512
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    entrypoint: [ "" ]
    command: sh -c "/opt/couchbase/init/init-cbserver.sh"
    networks:
      - tnet

volumes:
  dbdata:

networks:
  tnet:
    driver: bridge
